site_name: Портфолио nchskl
site_url: https://nchskl.github.io/
nav:
  - Home: index.md
  - Projects:
      - Project 1: projects/project1.md
      - Project 2: projects/project2.md
      - Project 3: projects/project3.md
  - Contacts: contacts.md
